### ISSUE TITLE
8.2 as requirement?

### ISSUE THREAD

**Issue by hashimaziz1** [sweikenb/pcntl#10]
Hi, just wondering what the reasoning is for version 4 and beyond requiring PHP 8.2 as minimum given that it only had a general release a few months ago and the majority of applications won't be moving to it for at least another year or so. Those versions seem to add a lot of good features and crucial bug fixes, so it seems a shame not to have these available to the majority of PHP applications just for the PHP 8.2 requirement.

**Comment by FelipeAzambuja** [comment]
i belive the correct php version is 7.4 looking the code
you shoud try run  composer require "sweikenb/pcntl" --ignore-platform-reqs

**Comment by sweikenb** [comment]
Sorry for the late reply, you might use this library with earlier versions of PHP such as 7.4 but due to further development, compatibility is not guaranteed.
